### ISSUE TITLE
Good resource for troubleshooting build?

### ISSUE THREAD

**Issue by ryaneroth** [eduardocasino/kim-1#1]
Have you found any good resource for troubleshooting your build? I've completed mine, but I am getting nothing on the display. The signals on the 6502 appear to be correct, according to the user manual, but I'm looking for a better reference for testing signals around the board.

This is what I am currently using http://retro.hansotten.nl/uploads/6502docs/hwman.htm#34

(update)

My testing so far is leading me to something on the 6532 adapter board

**Comment by eduardocasino** [comment]
I was lucky enough to have mine working at first try, so did not really have to do any troubleshooting. There is some information [on this thread](https://www.forum64.de/index.php?thread/124855-instandsetzung-und-nachbau-eines-kim-1/) (in German, but Google does a good job translating)

Excuse me if this is too obvious for you (EDIT: I've now seen your repo and I'm sure it is obvious, sorry), but make sure that the DECEN signal is connected to ground (pins K and 1 of the application connector) and that you press the reset key after powering up.

Also, as you suspect the adapter board, could you please upload the full contents of the 8K EPROM so I can check that they are correct?

**Comment by ryaneroth** [comment]
Thank you for the link to the forum.

I am 99% sure I have pins K and 1 connected. From what I can tell, due to the skipping of some letters, pin K is the 9th pin on the back side of the application connector.

I am pressing the reset key, and I can see the signal on LM311.

Here is a zipped dump of the ROM.  I've compared it to my PAL-1 ROM and it is 1 byte different, but my PAL-1 operates correctly with it: 
[KIM-1-ROM.dump.zip](https://github.com/eduardocasino/kim-1/files/13587596/KIM-1-ROM.dump.zip)

From what I can tell, the RIOT isn't ever pulling any of the inputs on the 74LS145 low. I am currently checking all the traces on the adapter board to make sure there isn't a bad connection somewhere.

Thanks again for the help.

**Comment by eduardocasino** [comment]
I think I see the problem. You have to program the EPROM starting at offset $1800, as instructed in [this issue](https://github.com/eduardocasino/kim-1-dual-6532-adapter/issues/1#issuecomment-1817937785). Yours starts at $0000.

**Comment by ryaneroth** [comment]
I missed that at some point when re-flashing the EPROM, but even with that corrected, I'm seeing the same behavior.  Going to continue scoping out the adapter board.

[KIM-1-ROM.dump.zip](https://github.com/eduardocasino/kim-1/files/13588395/KIM-1-ROM.dump.zip)

Thanks

**Comment by eduardocasino** [comment]
Try swapping the two RIOTs, the lower one (U2) is responsible for operating the display and keyboard. Also, do you have a way to test the memories? If not, you can use [this arduino based tester](https://www.8bity.cz/2013/jednoduchy-arduino-test-sram-mhb2102a-a-mm1101a/).

**Comment by ryaneroth** [comment]
Just to circle back, I have four RIOTs, and I've tested them all in my PAL-1. I built the RAM tester, and sure enough, one of my modules fails 100% of the time for every bit.  I don't have any spares, so I am waiting on a replacement.  I'll update once I've installed a known good replacement.

**Comment by ryaneroth** [comment]
Received some new RAM finally, fixed it!
